=== BISONNL/KV4/xsd/kv4-msg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- Copyright: Dit document is eigendom van platform BISON onder Samenwerkingsverband DOVA, -->
<!--            wordt geplubliceerd on de Creative Commons Licencsie by-nd/3.0/nl, zie       -->
<!--            http://creativecommons.org/licemcmses/by-nd/3.0/nl                           -->
<!-- Opmerking: XSD is gebaseerd op TMI8 koppelvlak 4 versie 8.1.1                           -->
<!-- Version:   0.1 (concept) (20-01-2009)                                                   -->
<!--            0.2 (draft)   (08-04-2010)                                                   -->
<!--            0.3 (concept) (dd-mm-2010)                                                   -->
<!--            0.4 (concept) (dd-mm-2010)                                                   -->
<!--            0.5 (concept) (dd-mm-2010)                                                   -->
<!-- History:                                                                                -->
<!--            0.1:   initiele versie 8.1.0.0(c)                                            -->
<!--            0.2:bijgewerkte versie 8.1.0.0(f)                                            -->
<!--            0.3:bijgewerkte versie 8.1.0.0(x)                                            -->
<!--            0.4:bijgewerkte versie 8.1.0.0(x)                                            -->
<!--            0.5:bijgewerkte versie 8.1.0.0(x)                                            -->
<!--            0.6:bijgewerkte versie 8.1.0.2                                               -->
<!--                  - aanpassen tikfout voor DossierNameType KV4relatedjourneys            -->
<!--                    was KV9relatedjourneys [Document was correct]                        -->
<!--         8.1.1a: Copyright aangepast.                                                    -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tmi8="http://bison.connekt.nl/tmi8/kv4/msg" xmlns:tmi8c="http://bison.connekt.nl/tmi8/kv4/core" targetNamespace="http://bison.connekt.nl/tmi8/kv4/msg" elementFormDefault="qualified">
	<xs:import namespace="http://bison.connekt.nl/tmi8/kv4/core" schemaLocation="kv4-core.xsd"/>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- TMI kv4 messages                                                                  -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:element name="VV_TM_PUSH">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties"/>
				<xs:element name="KV4relatedjourneys" type="tmi8:KV4relatedjourneysType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="VV_TM_REQ">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="VV_TM_RES">
		<xs:complexType>
			<xs:sequence>
				<xs:group ref="tmi8:MessageProperties" minOccurs="0"/>
				<xs:element name="ResponseCode" type="tmi8:ResponseCodeType"/>
				<xs:element name="ResponseError" type="tmi8:ResponseErrorType" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Dossiers: KV4relatedjourneys                                                      -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:complexType name="KV4relatedjourneysType">
		<xs:sequence>
			<xs:choice>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="RELATEDJOURNEY" type="tmi8:RELATEDJOURNEYType" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:choice>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- RELATEDJOURNEYS entities                                                          -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:complexType name="RELATEDJOURNEYType">
		<xs:sequence>
			<xs:element name="timestamp" type="tmi8:timestampType"/>
			<xs:element name="dataownercode" type="tmi8:daowcodeType"/>
			<xs:element name="operatingday" type="tmi8:tmidateType"/>
			<xs:element name="vehiclenumber" type="tmi8:vehicleidnumberType"/>
			<xs:element name="arrivingblockcode" type="tmi8:blockcodeType"/>
			<xs:element name="arrivinglineplanningnumber" type="tmi8:lineplanningnumberType"/>
			<xs:element name="arrivingjourneynumber" type="tmi8:journeynumberType"/>
			<xs:element name="arrivingreinforcementnumber" type="tmi8:reinforcementnumberType"/>
			<xs:element name="arrivingvehiclejourneytype" type="tmi8:vehiclejourneytypeType"/>
			<xs:element name="departingblockcode" type="tmi8:blockcodeType"/>
			<xs:element name="departinglineplanningnumber" type="tmi8:lineplanningnumberType"/>
			<xs:element name="departingjourneynumber" type="tmi8:journeynumberType"/>
			<xs:element name="departingreinforcementnumber" type="tmi8:reinforcementnumberType"/>
			<xs:element name="departingvehiclejourneytype" type="tmi8:vehiclejourneytypeType"/>
			<xs:element name="vehiclelength" type="tmi8:vehiclelengthType" minOccurs="0" maxOccurs="1"/>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="tmi8c:delimiter"/>
				<xs:any namespace="##targetNamespace ##local" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Message property types                                                            -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:group name="MessageProperties">
		<xs:sequence>
			<xs:element name="SubscriberID" type="tmi8:SubscriberIDType"/>
			<xs:element name="Version" type="tmi8:VersionType"/>
			<xs:element name="DossierName" type="tmi8:DossierNameType"/>
			<xs:element name="Timestamp" type="tmi8:TimestampType"/>
		</xs:sequence>
	</xs:group>
	<xs:simpleType name="DossierNameType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="KV4relatedjourneys"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="VersionType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SubscriberIDType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TimestampType">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="ResponseCodeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OK"/>
			<xs:enumeration value="NOK"/>
			<xs:enumeration value="SE"/>
			<xs:enumeration value="NA"/>
			<xs:enumeration value="PE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ResponseErrorType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<!-- Common entity types                                                               -->
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
	<xs:simpleType name="daowcodeType">
		<xs:annotation id="E1">
			<xs:documentation xml:lang="nl">
				Een en ander bepaalt volgens BISON enumeratie E1.
				Op dit moment bekende waardes zijn:
				Vervoerders: ARR, VTN, CXX, GVB, HTM, NS, RET, SYNTUS, QBUZZ, TCR,
				Integrators:  ALGEMEEN, GOVI, RIG, SABIMOS, PRORAIL, DRECHTSTED
				maar elke waarde is toegestaan
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="codeType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmidateType">
		<xs:annotation>
			<xs:documentation>Format: YYYY-MM-DD</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:date">
			<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			<!--
			<xs:minLength value="10"/>
			<xs:maxLength value="10"/> -->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmitimeType">
		<xs:annotation>
			<xs:documentation>Format: HH:MM:SS / H:MM:SS</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="7"/>
			<xs:maxLength value="8"/>
			<xs:pattern value="(0|1|2|3|4|5|6|7|8|9|00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31):[012345][0123456789]:[012345][0123456789]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tmidatetimeType">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="timestampType">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="vehicleidnumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="reinforcementnumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="99"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="journeynumberType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="blockcodeType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="99999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="lineplanningnumberType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="vehiclelengthType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="vehiclejourneytypeType">
		<xs:annotation id="E42">
			<xs:documentation xml:lang="nl">
				Geeft het soort rit aan, 
				DEADRUN = materiaalrit, geen passagiers
				SERVICEJOURNEY = dienstregelingrit (incluis versterkingrit), vervoert passagiers
				SPECIALSERVICE = bijzondere rit, overig, maar vervoert passagiers (bv pendel)
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="DEADRUN"/>
			<xs:enumeration value="SERVICEJOURNEY"/>
			<xs:enumeration value="SPECIALSERVICE"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
</xs:schema>

=== BISONNL/KV4/xml/tmi8_relatedjourneys_811_met_schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<tmi8:VV_TM_PUSH xsi:schemaLocation="http://bison.connekt.nl/tmi8/kv4/msg kv4-msg.xsd" xmlns:tmi8c="http://bison.connekt.nl/tmi8/kv4/core" xmlns:tmi8="http://bison.connekt.nl/tmi8/kv4/msg" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<tmi8:SubscriberID>ONBEKEND</tmi8:SubscriberID>
	<tmi8:Version>8.1.1</tmi8:Version>
	<tmi8:DossierName>KV4relatedjourneys</tmi8:DossierName>
	<tmi8:Timestamp>2009-11-20T13:19:00Z</tmi8:Timestamp>
	<tmi8:KV4relatedjourneys>
		<!-- twee elementen, een zonder en een uitbreiding -->
		<tmi8:RELATEDJOURNEY>
			<!-- element zonder uitbreiding -->
			<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
			<tmi8:dataownercode>abcdefghij</tmi8:dataownercode>
			<tmi8:operatingday>2009-11-20</tmi8:operatingday>
			<tmi8:vehiclenumber>123456</tmi8:vehiclenumber>
			<tmi8:arrivingblockcode>12345678</tmi8:arrivingblockcode>
			<tmi8:arrivinglineplanningnumber>abcdefghij</tmi8:arrivinglineplanningnumber>
			<tmi8:arrivingjourneynumber>123456</tmi8:arrivingjourneynumber>
			<tmi8:arrivingreinforcementnumber>99</tmi8:arrivingreinforcementnumber>
			<tmi8:arrivingvehiclejourneytype>SERVICEJOURNEY</tmi8:arrivingvehiclejourneytype>
			<tmi8:departingblockcode>12345678</tmi8:departingblockcode>
			<tmi8:departinglineplanningnumber>jihgfedcba</tmi8:departinglineplanningnumber>
			<tmi8:departingjourneynumber>654321</tmi8:departingjourneynumber>
			<tmi8:departingreinforcementnumber>00</tmi8:departingreinforcementnumber>
			<tmi8:departingvehiclejourneytype>SERVICEJOURNEY</tmi8:departingvehiclejourneytype>
			<!-- optionele veld -->
			<tmi8:vehiclelength>123</tmi8:vehiclelength>
		</tmi8:RELATEDJOURNEY>
		<tmi8:RELATEDJOURNEY>
			<!-- element met uitbreiding -->
			<tmi8:timestamp>2001-12-17T09:30:47Z</tmi8:timestamp>
			<tmi8:dataownercode>abcdefghij</tmi8:dataownercode>
			<tmi8:operatingday>2009-11-20</tmi8:operatingday>
			<tmi8:vehiclenumber>123456</tmi8:vehiclenumber>
			<tmi8:arrivingblockcode>12345678</tmi8:arrivingblockcode>
			<tmi8:arrivinglineplanningnumber>abcdefghij</tmi8:arrivinglineplanningnumber>
			<tmi8:arrivingjourneynumber>123456</tmi8:arrivingjourneynumber>
			<tmi8:arrivingreinforcementnumber>99</tmi8:arrivingreinforcementnumber>
			<tmi8:arrivingvehiclejourneytype>SERVICEJOURNEY</tmi8:arrivingvehiclejourneytype>
			<tmi8:departingblockcode>12345678</tmi8:departingblockcode>
			<tmi8:departinglineplanningnumber>jihgfedcba</tmi8:departinglineplanningnumber>
			<tmi8:departingjourneynumber>654321</tmi8:departingjourneynumber>
			<tmi8:departingreinforcementnumber>00</tmi8:departingreinforcementnumber>
			<tmi8:departingvehiclejourneytype>SERVICEJOURNEY</tmi8:departingvehiclejourneytype>
			<!-- optionele veld -->
			<tmi8:vehiclelength>123</tmi8:vehiclelength>
			<!-- uitbreidings veld -->
			<tmi8c:delimiter since="String"/>
			<!-- uitbreidingen vinden hier plaats -->
			<uitbreiding>voor toekomstige velden in het element</uitbreiding>
		</tmi8:RELATEDJOURNEY>
		<tmi8c:delimiter since="String"/>
		<!-- extra elementen worden hierachter ingeschoven -->
		<tmi8:TOEKOMSTIGELEMENT>
			<tmi8:toekomstigeveldeninhettoekomstigelement>INFORMATIE</tmi8:toekomstigeveldeninhettoekomstigelement>
		</tmi8:TOEKOMSTIGELEMENT>
	</tmi8:KV4relatedjourneys>
</tmi8:VV_TM_PUSH>
